Feat change to tekton output
boomerang-io/worker.box pull request #6
Opened 2022-03-09 13:35 UTC by cosmin-costache

Closes #5 

#### Changelog

**New**

- added a new method to mask sensitive parameter values in logs. A default list of parameters is defined in EssentialsUtils class.

**Changed**

- added option --outputFilePath to 'list' command. If the additional parameter contains a valid file path, the task output will be written to this file
- added option --outputFilePath to 'info' command. Same as for the list command.
- updated log statements to use the new method for masking the parameter values.

2022-03-10 13:34 UTC, morarucostel commented
Hey @cosmin-costache , thanks for the contribution.
Looks good to me.
Were you able to test it as part of a Task in a workflow?

2022-03-18 14:39 UTC, morarucostel approved these changes

2022-03-18 14:45 UTC, morarucostel commented
@georgesafta can you please provide the +1 ?

2022-03-18 15:20 UTC, georgesafta requested changes
Also, can you please format the code using the Google formater from here : https://github.com/google/styleguide. Choose the java one suitable to your IDE.

2022-03-18 15:20 UTC, georgesafta commented on src/main/java/com/ibm/garage/box/command/BoxCommand.java
> +      if(outputFilePath != null && !outputFilePath.isEmpty()) {
can you please use the Apache `StringUtils.isNotBlank` method here?

2022-03-18 15:20 UTC, georgesafta commented on src/main/java/com/ibm/garage/box/command/BoxCommand.java
> +      if(outputFilePath != null && !outputFilePath.isEmpty()) {
can you please use the Apache `StringUtils.isNotBlank` method here?

2022-03-18 15:20 UTC, georgesafta commented on src/main/java/com/ibm/garage/box/command/BoxCommand.java
> +        LOGGER.info(String.format("Saving task output to file %s", outputFilePath));
no need for String.format here, you can use the SLF4J API directly here by:
```
LOGGER.info("Saving task output to file {}", outputFilePath);
```

2022-03-21 16:35 UTC, georgesafta approved these changes

2022-03-21 16:37 UTC, merged

2022-05-19 08:44 UTC, morarucostel commented
Closing issue #5